// alert("Click proceed to continue");
console.time("Time taken");
console.log("Hello World !");
console.group();
console.log("Hello again, to say thanks");
console.log("we are here to support you !!!");
console.groupEnd();
console.log("and we are back.");
// console.groupCollapsed();
// console.log("Hello again, to say thanks");
// console.log("we are here to support you !!!");
console.info('welcome');
console.log(document.head);
console.log(document.body);
console.log(document.url);
console.log("welcome to JS");
console.error("An error occured");
console.warn("An warning message");
console.trace("An Exception Occured");
var student1 = {'name':'Aswin', 'class':9,'rank':5,'subject':'maths'};
var student2 = {'name':'karthick', 'class':10,'rank':1,'subject':'sciencr'};
var student3 = {'name':'vignesh', 'class':11,'rank':3,'subject':'English'};
var student4 = {'name':'spidy', 'class':8,'rank':6,'subject':'social'};
// console.log(student1);
// console.log(student2);
// console.log(student3);
// console.log(student4);
console.log({student1,student2,student3,student4});
console.table({student1,student2,student3,student4});
console.log('%c custom message','color:violet');
console.assert(document.getElementById("demo"),student1);
// console.clear();
console.timeEnd("Time taken");
